export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const DECLARATION = 'DECLARATION'
export const PIN_SETTING = 'PIN_SETTING'
export const DETAIL_INFOR_SETTING = 'DETAIL_INFOR_SETTING'
export const MODAL_VIEW = 'MODAL_VIEW'